[package]
name = "outboard-demo-engine-echo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "outboard-demo-engine-echo"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
clap.workspace = true
outboard.workspace = true
outboard-clap.workspace = true
outboard-tokio.workspace = true
outboard-demo-api = { path = "../demo-api" }
semver.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
